version: 0.2
phases:
  install:
    commands:
      # memo: Is choco installed ?
      - choco install fvm
      - fvm install 2.5.0
      - fvm use 2.5.0
      - fvm flutter config --enable-windows-desktop
  build:
    commands:
      - fvm flutter pub get
      - fvm flutter pub run build_runner build
      - fvm flutter build windows
